from MIDIMusicScales import Scales

class lemon:

    def __init__(self):
        self.name = "Lemon"
        self.lemon = Scales(200)

    def generator(self):
        #-----音乐部分-----#
        with open("{}.MID".format(self.name), "wb") as output_file:
            self.lemon.get_midi().writeFile(output_file)
        return self.name

    def generator(self):
        #------- 1 -------#
        self.lemon.g5(3)
        self.lemon.e5(1.2)
        self.lemon.g5(1.2)
        self.lemon.e5(1.2)
        self.lemon.g5(3)
        self.lemon.modify_time(-9.6)
        self.lemon.c4(9.4)
        self.lemon.modify_time(-9.6)
        self.lemon.e4(9.4)
        self.lemon.modify_time(-9.6)
        self.lemon.g4(9.4)
        #------- 1s -------#
        self.lemon.modify_time(-9.6)
        self.lemon.e4(3)
        self.lemon.c4(1.2)
        self.lemon.e4(1.2)
        self.lemon.c4(1.2)
        self.lemon.e4(3)
        #------- 2 -------#
        self.lemon.a5(1.1)
        self.lemon.g5(1)
        self.lemon.e5(1.65)
        self.lemon.a5(1.1)
        self.lemon.g5(5)

        #------- 2s -------#
        self.lemon.modify_time(-9.8)
        self.lemon.c4(1.1)
        self.lemon.d4(1)
        self.lemon.e4(1.65)
        self.lemon.f4(1.1)
        self.lemon.e4(5)
        # ------- 3 -------
        self.lemon.c5(1.6)
        self.lemon.c5(1)
        self.lemon.d5(1)
        self.lemon.e5(1.5)
        self.lemon.g5(1)
        self.lemon.e5(1)
        self.lemon.d5(3)
        self.lemon.e5(0.9)
        self.lemon.g5(3)
        # ------- 3s -------#
        self.lemon.modify_time(-14)
        self.lemon.a3(1.6)
        self.lemon.a3(1)
        self.lemon.b3(1)
        self.lemon.c4(1.5)
        self.lemon.e4(1)
        self.lemon.c4(1)
        self.lemon.d4(3)
        self.lemon.c4(0.9)
        self.lemon.d4(3)
        # ------- 4 -------#
        self.lemon.g5(1)
        self.lemon.g5(1.1)
        self.lemon.a5(1)
        self.lemon.g5(1.1)
        self.lemon.e5(1.1)
        self.lemon.g5(2)
        self.lemon.g5(1)
        self.lemon.a5(1)
        self.lemon.g5(1)
        self.lemon.c6(1)
        self.lemon.a5(1)
        self.lemon.g5(3)
        #------- 4s -------#
        self.lemon.modify_time(-15.3)
        self.lemon.e4(1)
        self.lemon.e4(1.1)
        self.lemon.f4(1)
        self.lemon.e4(1.1)
        self.lemon.c4(1.1)
        self.lemon.e4(2)
        self.lemon.e4(1)
        self.lemon.f4(1)
        self.lemon.g4(1)
        self.lemon.a4(1)
        self.lemon.f4(1)
        self.lemon.g4(3)

        #------- 5 -------#
        self.lemon.c5(2)
        self.lemon.g5(1.1)
        self.lemon.e5(1)
        self.lemon.d5(1.1)
        self.lemon.c5(1.1)
        self.lemon.d5(2)
        self.lemon.e5(1)
        self.lemon.g5(3)
        self.lemon.d5(1)
        self.lemon.e5(2)
        self.lemon.c5(10)
        #------- 5s -------#
        self.lemon.modify_time(-25)
        self.lemon.c4(2)
        self.lemon.e4(1.1)
        self.lemon.c4(1)
        self.lemon.d4(1.1)
        self.lemon.c4(1.1)
        self.lemon.d4(2)
        self.lemon.c4(1)
        self.lemon.e4(1)
        self.lemon.d4(1)
        self.lemon.c4(1)
        self.lemon.b3(0.7)
        self.lemon.b3(0.7)
        self.lemon.b3(1.5)
        self.lemon.c4(10)

        # ------- 6 -------#
        self.lemon.g5(2)
        self.lemon.e6(2)
        self.lemon.d6(1.5)
        self.lemon.c6(1)
        self.lemon.a5(1.1)
        self.lemon.g5(1)
        self.lemon.g5(3)
        # ------- 6s -------#
        self.lemon.modify_time(-11.6)
        self.lemon.g4(2)
        self.lemon.g5(2)
        self.lemon.g4(1.5)
        self.lemon.g4(1)
        self.lemon.f4(1.1)
        self.lemon.e4(1)
        self.lemon.e4(3)
        # ------- 7 -------#
        self.lemon.a5(1)
        self.lemon.a5(2)
        self.lemon.g5(1)
        self.lemon.a5(1.5)
        self.lemon.c6(0.5)
        self.lemon.e6(1)
        self.lemon.c6(1)
        self.lemon.d6(4)
        # ------- 7s -------#
        self.lemon.modify_time(-12)
        self.lemon.e4(1)
        self.lemon.e5(2)
        self.lemon.e4(1)
        self.lemon.e4(1.2)
        self.lemon.g4(0.8)
        self.lemon.a4(1.2)
        self.lemon.g4(0.8)
        self.lemon.f4s(4)
        # ------- 8 -------#
        self.lemon.g5(1.2)
        self.lemon.e6(2)
        self.lemon.d6(1.5)
        self.lemon.c6(0.5)
        self.lemon.a5(1)
        self.lemon.g5(1)
        self.lemon.g5(2.5)
        self.lemon.a5(1)
        self.lemon.a5(2)
        self.lemon.g5(1)
        self.lemon.a5(1.7)
        self.lemon.e6(2)
        self.lemon.d6(5)
        # ------- 8s -------#
        self.lemon.modify_time(-22.4)
        self.lemon.g4(2.6)
        self.lemon.g4(2.3)
        self.lemon.g4(0.5)
        self.lemon.f4(1)
        self.lemon.e4(1)
        self.lemon.e4(2.5)
        self.lemon.e4(1)
        self.lemon.e4(2)
        self.lemon.e4(1)
        self.lemon.e4(1.7)
        self.lemon.a4(2)
        self.lemon.g4(5)

        # ------- 9 -------#
        self.lemon.e6(2)
        self.lemon.d6(1.5)
        self.lemon.c6(1)
        self.lemon.a5(1.2)
        self.lemon.g5(1.2)
        self.lemon.g5(2)
        self.lemon.c6(2)
        self.lemon.a5(1)
        self.lemon.g5(1)
        self.lemon.e5(1.2)
        self.lemon.d5(1.2)
        self.lemon.c5(3)
        # ------- 9s -------#
        self.lemon.modify_time(-18.3)
        self.lemon.g4(2)
        self.lemon.g4(1.5)
        self.lemon.g4(1)
        self.lemon.f4(1.2)
        self.lemon.e4(1.2)
        self.lemon.e4(2)
        self.lemon.f4(2)
        self.lemon.e4(1)
        self.lemon.d4(1)
        self.lemon.c4(1.2)
        self.lemon.b3(1.2)
        self.lemon.c4(3)
        # ------- 10 -------#
        self.lemon.d5(1.2)
        self.lemon.e5(1.2)
        self.lemon.g5(3)
        self.lemon.modify_time(-5.4)
        self.lemon.b3(1.2)
        self.lemon.c4(1.2)
        self.lemon.d4(3)
        self.lemon.modify_time(-1.2)
        self.lemon.d6(1.2)
        self.lemon.e6(1.2)
        self.lemon.g6(3)
        # ------- 11 -------#
        self.lemon.g5(1.6)
        self.lemon.a5(1)
        self.lemon.c6(8)
        self.lemon.modify_time(-10.6)
        self.lemon.e4(1.6)
        self.lemon.f4(1)
        self.lemon.g4(8)
        self.lemon.modify_time(-8)
        self.lemon.c3(8)
        self.lemon.modify_time(-8)
        self.lemon.e3(8)
        self.lemon.modify_time(-8)
        self.lemon.g4(8)
        with open("{}.MID".format(self.name), "wb") as output_file:
            self.lemon.get_midi().writeFile(output_file)
        return self.name